apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: interviewsync-backend-production
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://github.com/EyalLin2/InterviewSync
      targetRevision: main
      path: backend/charts
      helm:
        valueFiles:
          - $values/apps/production/backend-values.yaml
    - repoURL: https://github.com/EyalLin2/interviewsync-gitops
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: production
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
