apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: interviewsync-postgres-production
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://charts.bitnami.com/bitnami
      chart: postgresql
      targetRevision: "15.5.17"
      helm:
        valueFiles:
          - $values/apps/production/postgres-values.yaml
    - repoURL: https://github.com/EyalLin2/interviewsync-gitops
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: production
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
