apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: interviewsync-frontend-staging
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://github.com/EyalLin2/InterviewSync
      targetRevision: main
      path: frontend/charts
      helm:
        valueFiles:
          - $values/apps/staging/frontend-values.yaml
    - repoURL: https://github.com/EyalLin2/interviewsync-gitops
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
