apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: interviewsync-postgres-staging
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: postgresql
    targetRevision: "15.5.17"
    helm:
      valueFiles:
        - https://raw.githubusercontent.com/<YOUR_USERNAME>/interviewsync-gitops/main/apps/staging/postgres-values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: staging
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
